services:
  db:
    image: postgres:17
    container_name: finflow-db

    environment:
      POSTGRES_USER: finflow
      POSTGRES_PASSWORD: finflow
      POSTGRES_DB: finflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: